version: '3.9'

services:
  frontend:
    build: ./frontend
    image: 2real2be2real/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: 2real2be2real/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
      - postgres
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  postgres:
    image: postgres:15
    container_name: smart-workorders-db-1
    ports:
      - "5432:5432"
    # Use the same .env file for the database credentials.
    env_file:
      - ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: