services:
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - "3000:3000"
      - "9091:9091" # Added metrics port
    depends_on:
      - backend

  backend:
    build: ./backend
    image: backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - mqtt
      - postgres
    environment:
      - MQTT_BROKER=mqtt
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=smartops
      - DATABASE_PASSWORD=smartops123

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smartops
      POSTGRES_PASSWORD: smartops123
      POSTGRES_DB: smartops
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
