name: SmartOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        run: |
          # replace with actual pytest commands when you add tests
          echo "No backend tests yet!"

      - name: Build backend Docker image
        run: |
          docker build -t backend:latest ./backend

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Build frontend Docker image
        run: docker build -t frontend:latest ./frontend

  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    needs: frontend
    steps:

      # ---------------- Optional Minikube Dry-Run ----------------
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.13.0
        with:
          minikube version: 'v1.36.0'
          driver: docker
          kubernetes version: 'v1.29.0' 

      - name: Minikube Dry Run
        shell: bash
        run: |
          echo "=== MINIKUBE DRY-RUN ==="
          echo "Purpose: Spin up SmartOps stack in Minikube for demo/testing"
          
          minikube start --driver=docker
          minikube addons enable ingress

          echo "Loading backend and frontend images..."
          minikube image load frontend:latest
          minikube image load backend:latest

          echo "Applying Kubernetes manifests..."
          kubectl apply -f k8s/

          echo "Listing pods, services, and ingress..."
          kubectl get pods
          kubectl get svc
          kubectl get ingress

      # ---------------- Optional Docker Compose Dry-Run ----------------
      - name: Docker Compose Dry-Run Demo
        shell: bash
        continue-on-error: true
        run: |
          echo "=== DOCKER COMPOSE DRY-RUN ==="
          echo "Purpose: Spin up full SmartOps stack locally for demo/testing"
          
          # Build & start all services
          docker-compose -f docker-compose.yml up --build --detach
          
          echo "Listing running containers..."
          docker-compose ps

          echo "Sleeping 10 seconds to allow services to start..."
          sleep 10

          echo "Checking basic connectivity to backend and frontend services..."
          docker-compose exec backend curl -f http://localhost:8000 || echo "Backend not ready"
          docker-compose exec frontend curl -f http://localhost:3000 || echo "Frontend not ready"

          echo "Stopping all containers..."
          docker-compose down
          echo "=== DOCKER COMPOSE DRY-RUN COMPLETE ==="
